language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python setup.py develop
  - cveminer -d < password.txt
  - cveminer -db < password.txt
  - pytest -s < password.txt --cov=cveminer tests/